version: '3.8'

services:

  db:
    image: postgres:latest
    volumes:
      - ./pgsql/:/var/lib/postgresql/data/:z
    env_file:
      - ./env.txt
    expose:
      - 5432

  django:
    build:
      context: ./ask_a_furry/
      dockerfile: Dockerfile
    volumes:
      - ./ask_a_furry/:/usr/src/app/:z
      - ./ask_a_furry/static/:/usr/src/app/static/:z
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./env.txt

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./ask_a_furry/static/:/usr/src/app/static/:z
    depends_on:
      - django

