# Generated by Django 4.1.5 on 2023-01-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_alter_question_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='full_text',
            field=models.CharField(max_length=512),
        ),
    ]
